"""Autonomous Research Intelligence — Research Planner, Source Discovery, and Collection.

The deterministic planning, selection, and collection layer that, for a
given company:

* Decides what information is missing (Research Planner, Sprint 1),
* Decides what research to perform (Research Planner, Sprint 1),
* Orders that research (Research Planner, Sprint 1),
* Selects the highest-quality candidate sources (Source Discovery,
  Sprint 2),
* Executes the research by orchestrating placeholder collectors and
  aggregating deterministic evidence (Evidence Collection, Sprint 3).

The package is **pure planning and collection**: no network scraping, no
search APIs, no browser automation, no LLMs, and no live evidence.
Every layer is deterministic — the same input always produces the same
plan, the same ranked source recommendations, and the same collection
result.
"""

from predictron_engine.research.collector import (
    EvidenceCollector,
    enforce_supported,
)
from predictron_engine.research.collectors import (
    DEFAULT_COLLECTORS,
    PLACEHOLDER_EVIDENCE_ORIGIN,
    ClaimSpec,
    CompetitionCollector,
    CustomerCollector,
    FounderCollector,
    FundingCollector,
    HiringCollector,
    LegalCollector,
    MarketCollector,
    NewsCollector,
    PartnershipCollector,
    PlaceholderCollector,
    PricingCollector,
    ProductCollector,
    ReviewsCollector,
    RiskCollector,
    TechnologyCollector,
    TractionCollector,
)
from predictron_engine.research.dispatcher import (
    CollectorDispatch,
    Dispatcher,
    DispatchPlan,
)
from predictron_engine.research.exceptions import (
    CollectorExecutionError,
    CollectorNotFound,
    DependencyCycleError,
    DuplicateCollector,
    InvalidCollectionInputError,
    InvalidDiscoveryInputError,
    InvalidEvidence,
    InvalidPlannerInputError,
    ResearchError,
    RuleRegistrationError,
    SourceRegistryError,
    UnknownSourceError,
    UnknownTopicError,
    UnsupportedTopic,
)
from predictron_engine.research.execution import EvidenceCollectionEngine
from predictron_engine.research.models import (
    COLLECTION_SCHEMA_VERSION,
    PLAN_SCHEMA_VERSION,
    SOURCE_SCHEMA_VERSION,
    CollectionResult,
    CollectionStatus,
    Evidence,
    EvidenceCollection,
    EvidenceMetadata,
    EvidenceReference,
    EvidenceStatus,
    KnowledgeGap,
    PlannerInput,
    ResearchPlan,
    ResearchPriority,
    ResearchSource,
    ResearchTask,
    ResearchTopic,
    SourceCategory,
    SourceDiscoveryPlan,
    SourceRank,
    SourceRecommendation,
    SourceScore,
)
from predictron_engine.research.planner import (
    ResearchPlanner,
    recommend_topics,
)
from predictron_engine.research.priorities import (
    DEPENDENCY_WEIGHT,
    FRESHNESS_WEIGHT,
    IMPORTANCE_WEIGHT,
    MISSING_EVIDENCE_WEIGHT,
    PREDICTION_IMPACT_WEIGHT,
    SOURCE_AVAILABILITY_WEIGHT,
    compute_priority_score,
    evidence_missing_factor,
    horizon_freshness_scale,
    priority_from_score,
    source_availability_factor,
)
from predictron_engine.research.registry import (
    COLLECTOR_REGISTRY,
    CollectorRegistry,
    collectors_for,
    covered_topics,
    default_collector_registry,
    has_collector,
    list_collectors,
    register_collector,
    resolve_collector,
    unregister_collector,
)
from predictron_engine.research.rules import (
    DEFAULT_RULES,
    CoverageRule,
    MissingFoundersRule,
    MissingFundingRule,
    MissingMarketRule,
    MissingPricingRule,
    MissingTechnologyRule,
    ResearchRule,
    coverage_status,
    evaluate_rules,
    register_rule,
    registered_rules,
    research_rules,
)
from predictron_engine.research.source_discovery import SourceDiscovery
from predictron_engine.research.source_ranker import (
    COST_WEIGHT,
    COVERAGE_WEIGHT,
    RANKING_WEIGHTS,
    STRUCTURED_WEIGHT,
    TRUST_WEIGHT,
    compute_source_score,
    freshness_priority_scale,
    rank_sources,
    topic_fit_factor,
)
from predictron_engine.research.source_ranker import (
    FRESHNESS_WEIGHT as RANKING_FRESHNESS_WEIGHT,
)
from predictron_engine.research.source_registry import (
    DEFAULT_DISCOVERY_RULES,
    SOURCE_CATALOG,
    SOURCE_REGISTRY,
    SourceDiscoveryRule,
    SourceRegistry,
    all_sources,
    candidate_sources,
    categories,
    discovery_rules,
    get_source,
    has_source,
    rule_for_topic,
    source_index,
    sources_by_category,
)
from predictron_engine.research.topics import (
    RESEARCH_TOPICS,
    SOURCE_CATEGORIES,
    SOURCE_CATEGORY_DESCRIPTIONS,
    TOPIC_REGISTRY,
    all_topic_ids,
    dependency_edges,
    get_topic,
    has_topic,
    topic_index,
)

__all__ = [
    "COLLECTION_SCHEMA_VERSION",
    "COLLECTOR_REGISTRY",
    "COST_WEIGHT",
    "COVERAGE_WEIGHT",
    "ClaimSpec",
    "CollectionResult",
    "CollectionStatus",
    "CollectorDispatch",
    "CollectorExecutionError",
    "CollectorNotFound",
    "CollectorRegistry",
    "CompetitionCollector",
    "CoverageRule",
    "CustomerCollector",
    "DEFAULT_COLLECTORS",
    "DEFAULT_DISCOVERY_RULES",
    "DEFAULT_RULES",
    "DEPENDENCY_WEIGHT",
    "DependencyCycleError",
    "DispatchPlan",
    "Dispatcher",
    "DuplicateCollector",
    "Evidence",
    "EvidenceCollection",
    "EvidenceCollectionEngine",
    "EvidenceCollector",
    "EvidenceMetadata",
    "EvidenceReference",
    "EvidenceStatus",
    "FRESHNESS_WEIGHT",
    "FounderCollector",
    "FundingCollector",
    "HiringCollector",
    "IMPORTANCE_WEIGHT",
    "InvalidCollectionInputError",
    "InvalidDiscoveryInputError",
    "InvalidEvidence",
    "InvalidPlannerInputError",
    "KnowledgeGap",
    "LegalCollector",
    "MISSING_EVIDENCE_WEIGHT",
    "MarketCollector",
    "MissingFoundersRule",
    "MissingFundingRule",
    "MissingMarketRule",
    "MissingPricingRule",
    "MissingTechnologyRule",
    "NewsCollector",
    "PLACEHOLDER_EVIDENCE_ORIGIN",
    "PLAN_SCHEMA_VERSION",
    "PREDICTION_IMPACT_WEIGHT",
    "PartnershipCollector",
    "PlaceholderCollector",
    "PlannerInput",
    "PricingCollector",
    "ProductCollector",
    "RANKING_WEIGHTS",
    "RANKING_FRESHNESS_WEIGHT",
    "RESEARCH_TOPICS",
    "ReviewsCollector",
    "RiskCollector",
    "RuleRegistrationError",
    "SOURCE_AVAILABILITY_WEIGHT",
    "SOURCE_CATALOG",
    "SOURCE_CATEGORIES",
    "SOURCE_CATEGORY_DESCRIPTIONS",
    "SOURCE_REGISTRY",
    "SOURCE_SCHEMA_VERSION",
    "STRUCTURED_WEIGHT",
    "SourceCategory",
    "SourceDiscovery",
    "SourceDiscoveryPlan",
    "SourceDiscoveryRule",
    "SourceRank",
    "SourceRecommendation",
    "SourceRegistry",
    "SourceRegistryError",
    "SourceScore",
    "TOPIC_REGISTRY",
    "TRUST_WEIGHT",
    "TechnologyCollector",
    "TractionCollector",
    "ResearchError",
    "ResearchPlan",
    "ResearchPlanner",
    "ResearchPriority",
    "ResearchRule",
    "ResearchSource",
    "ResearchTask",
    "ResearchTopic",
    "UnknownSourceError",
    "UnknownTopicError",
    "UnsupportedTopic",
    "all_sources",
    "all_topic_ids",
    "candidate_sources",
    "categories",
    "collectors_for",
    "compute_priority_score",
    "compute_source_score",
    "coverage_status",
    "covered_topics",
    "default_collector_registry",
    "dependency_edges",
    "discovery_rules",
    "enforce_supported",
    "evaluate_rules",
    "evidence_missing_factor",
    "freshness_priority_scale",
    "get_source",
    "get_topic",
    "has_collector",
    "has_source",
    "has_topic",
    "horizon_freshness_scale",
    "list_collectors",
    "priority_from_score",
    "rank_sources",
    "recommend_topics",
    "register_collector",
    "register_rule",
    "registered_rules",
    "research_rules",
    "resolve_collector",
    "rule_for_topic",
    "source_availability_factor",
    "source_index",
    "sources_by_category",
    "topic_fit_factor",
    "topic_index",
    "unregister_collector",
]
