"""Pydantic schemas for the Live Prediction Ledger (CIH Phase 5).

Additive request/response schemas for the deterministic forecast lifecycle.
Frozen prediction data is echoed as opaque JSON (``prediction``) so the
ledger stays forward-compatible; response models are deliberately separate
from the ORM models.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class ForecastCreateRequest(BaseModel):
    """Payload for registering one forecast against a frozen snapshot."""

    company_id: str = Field(..., description="Owning company identifier")
    snapshot_id: str = Field(
        ..., description="Immutable analysis snapshot the forecast is pinned to"
    )
    horizon_days: int | None = Field(
        default=None,
        gt=0,
        description="Evaluation horizon in days; defaults to the server setting",
    )
    notes: str = Field(default="", description="Free-text notes")


class ForecastEventResponse(BaseModel):
    """One append-only lifecycle event."""

    id: str = Field(..., description="Deterministic event identifier")
    forecast_id: str = Field(..., description="Owning forecast identifier")
    event_type: str = Field(..., description="registered | due | resolved")
    occurred_at: datetime = Field(..., description="When the event was recorded")
    payload: dict[str, object] | None = Field(
        default=None, description="Event payload (for example the resolved outcome)"
    )


class ForecastResponse(BaseModel):
    """One persisted forecast as stored (status is service-owned)."""

    id: str = Field(..., description="Deterministic forecast identifier")
    company_id: str = Field(..., description="Owning company identifier")
    snapshot_id: str = Field(..., description="Pinned analysis snapshot")
    outcome_id: str | None = Field(
        default=None, description="Attached outcome, once resolved"
    )
    analysis_timestamp: datetime = Field(..., description="Analysis the forecast is pinned to")
    due_at: datetime = Field(..., description="Earliest moment the outcome is due")
    horizon_days: int = Field(..., gt=0, description="Evaluation horizon in days")
    status: str = Field(..., description="Derived lifecycle status (active | due | resolved)")
    decision: str = Field(..., description="Engine decision at analysis time")
    confidence: float = Field(..., description="Snapshot confidence (0-1)")
    composite_score: float = Field(..., description="Snapshot composite score (0-100)")
    engine_version: str = Field(..., description="Engine version at registration")
    schema_version: str = Field(..., description="Ledger schema version at registration")
    reconciled_at: datetime | None = Field(
        default=None, description="When the forecast was matched to an outcome"
    )
    notes: str = Field(default="", description="Free-text notes")
    created_at: datetime = Field(..., description="When the forecast was registered")
    updated_at: datetime = Field(..., description="Last lifecycle update")


class ForecastDetailResponse(ForecastResponse):
    """Forecast detail: the row plus its frozen prediction and event log."""

    prediction: dict[str, object] = Field(
        ..., description="Frozen PredictionSummary captured at analysis time"
    )
    events: list[ForecastEventResponse] = Field(
        default_factory=list, description="Append-only lifecycle event log"
    )


class ForecastWriteResponse(BaseModel):
    """POST forecast response: the row plus idempotency info."""

    forecast: ForecastResponse = Field(..., description="The persisted forecast")
    created: bool = Field(
        ..., description="True when this submission inserted a new row"
    )


class ForecastReconcileResponse(BaseModel):
    """POST ``/forecasts/{id}/reconcile`` response."""

    forecast: ForecastResponse = Field(..., description="The reconciled forecast")
    outcome_id: str | None = Field(
        default=None, description="Outcome matched to this forecast, if any"
    )
    outcome_verdict: str | None = Field(
        default=None, description="Verdict of the matched outcome, if any"
    )
    evaluations_created: int = Field(
        default=0, ge=0, description="Prediction evaluations generated by this pass"
    )
    reconciled: bool = Field(
        default=False,
        description="True when this pass newly attached an outcome to the forecast",
    )


class ForecastBatchReconcileResponse(BaseModel):
    """POST ``/forecasts/reconcile`` response over every forecast in scope."""

    forecasts: list[ForecastResponse] = Field(
        default_factory=list, description="Every in-scope forecast after the pass"
    )
    reconciled_count: int = Field(
        default=0, ge=0, description="Forecasts newly matched to an outcome this pass"
    )


class ForecastListResponse(BaseModel):
    """Paginated forecast list (newest-first) matching the filters."""

    total: int = Field(default=0, ge=0, description="Forecasts matching the filters")
    forecasts: list[ForecastResponse] = Field(default_factory=list)
    offset: int = Field(default=0, ge=0)
    limit: int = Field(default=20, ge=1)


class ForecastSummaryResponse(BaseModel):
    """Ledger summary counts plus the most recent forecasts."""

    total: int = Field(default=0, ge=0, description="Forecasts in scope")
    by_status: dict[str, int] = Field(
        default_factory=dict, description="Count per lifecycle status"
    )
    active: int = Field(default=0, ge=0)
    due: int = Field(default=0, ge=0)
    resolved: int = Field(default=0, ge=0)
    outcome_linked: int = Field(
        default=0, ge=0, description="Forecasts matched to a recorded outcome"
    )
    recent: list[ForecastResponse] = Field(
        default_factory=list, description="Most recently registered forecasts"
    )
    generated_at: datetime = Field(..., description="When this view was generated")


__all__ = [
    "ForecastBatchReconcileResponse",
    "ForecastCreateRequest",
    "ForecastDetailResponse",
    "ForecastEventResponse",
    "ForecastListResponse",
    "ForecastReconcileResponse",
    "ForecastResponse",
    "ForecastSummaryResponse",
    "ForecastWriteResponse",
]
