"""Pydantic schemas for recording and listing company outcomes (CIH Phase 4).

Additive request/response schemas for the validity loop. Outcomes are
observed facts; the response echoes the derived verdict but never a
prediction. Response models are deliberately separate from the ORM models
so the API surface stays forward-compatible.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from predictron_engine.dataset.outcomes import StartupOutcome


class OutcomeCreateRequest(BaseModel):
    """Payload for recording a single real-world outcome for a company.

    ``outcome`` is the observed :class:`StartupOutcome` — only verified,
    non-fabricated facts. ``snapshot_id`` optionally pins the outcome to the
    snapshot (analysis) that preceded it; when omitted the outcome applies to
    every snapshot whose ``created_at`` predates ``occurred_at``.
    """

    outcome: StartupOutcome = Field(
        ...,
        description="Observed outcome facts (all fields allow unknown/None)",
    )
    snapshot_id: str | None = Field(
        default=None,
        description="Optional snapshot this outcome explains",
    )
    occurred_at: datetime | None = Field(
        default=None,
        description="When the outcome was observed; defaults to now (UTC)",
    )
    source: str = Field(
        default="manual",
        description="Origin of the outcome data",
    )
    notes: str = Field(
        default="", description="Free-text notes about this outcome"
    )


class CompanyOutcomeResponse(BaseModel):
    """One persisted outcome, echoed back to the caller."""

    id: str = Field(..., description="Deterministic outcome identifier")
    company_id: str = Field(..., description="Owning company identifier")
    snapshot_id: str | None = Field(
        default=None, description="Snapshot this outcome is pinned to, if any"
    )
    source: str = Field(..., description="Origin of the outcome data")
    occurred_at: datetime = Field(..., description="When the outcome was observed")
    time_horizon_days: int | None = Field(
        default=None, description="Days between the pinned snapshot and the outcome"
    )
    outcome: StartupOutcome = Field(
        ..., description="The recorded observed outcome facts"
    )
    verdict: str = Field(..., description="Derived outcome verdict (never predicted)")
    verdict_reasoning: str = Field(
        default="", description="Explanation of how the verdict was derived"
    )
    status: str = Field(..., description="Verification status of the outcome")
    notes: str = Field(default="", description="Free-text notes")
    created_at: datetime = Field(..., description="When the row was persisted")


class CompanyOutcomeWriteResponse(BaseModel):
    """POST outcome response: the row plus idempotency and evaluation info."""

    outcome: CompanyOutcomeResponse = Field(..., description="The persisted outcome")
    created: bool = Field(
        ..., description="True when this submission inserted a new row"
    )
    evaluations_created: int = Field(
        default=0,
        ge=0,
        description="Prediction evaluations generated by this submission",
    )


class CompanyOutcomeListResponse(BaseModel):
    """Paginated list of outcomes for one company (newest-first)."""

    company_id: str = Field(..., description="Owning company identifier")
    total: int = Field(default=0, ge=0, description="Outcomes recorded for the company")
    outcomes: list[CompanyOutcomeResponse] = Field(default_factory=list)


__all__ = [
    "CompanyOutcomeListResponse",
    "CompanyOutcomeResponse",
    "CompanyOutcomeWriteResponse",
    "OutcomeCreateRequest",
]
